import { Component } from '@angular/core';
import {LucideAngularModule} from "lucide-angular";
import {NgClass, NgForOf, NgIf} from "@angular/common";
import {Project} from "../../shared/model/util/types";

@Component({
  selector: 'app-table',
  standalone: true,
  imports: [
    LucideAngularModule,
    NgForOf,
    NgClass,
    NgIf
  ],
  templateUrl: './table.component.html',
  styleUrl: './table.component.scss'
})
export class TableComponent {

  projects: Project[] = [
    {
      id: 1,
      title: 'Website Redesign',
      description: 'Redesign the company website to improve UX',
      date: 'Feb 3, 2026',
      status: 'In Progress',
      statusColor: 'bg-blue-100 text-blue-700',
      priority: 'High',
      priorityColor: 'bg-red-100 text-red-700',
    },
    {
      id: 2,
      title: 'Mobile App',
      description: 'Build a cross-platform mobile application',
      date: 'Jan 18, 2026',
      status: 'Completed',
      statusColor: 'bg-green-100 text-green-700',
      priority: 'Medium',
      priorityColor: 'bg-orange-100 text-orange-700',
    },
    {
      id: 3,
      title: 'Data Dashboard',
      description: 'Analytics dashboard for KPIs and metrics',
      date: 'Mar 1, 2026',
      status: 'Pending',
      statusColor: 'bg-yellow-100 text-yellow-700',
      priority: 'Low',
      priorityColor: 'bg-gray-100 text-gray-700',
    },
    {
      id: 1,
      title: 'Website Redesign',
      description: 'Redesign the company website to improve UX',
      date: 'Feb 3, 2026',
      status: 'In Progress',
      statusColor: 'bg-blue-100 text-blue-700',
      priority: 'High',
      priorityColor: 'bg-red-100 text-red-700',
    },
    {
      id: 2,
      title: 'Mobile App',
      description: 'Build a cross-platform mobile application',
      date: 'Jan 18, 2026',
      status: 'Completed',
      statusColor: 'bg-green-100 text-green-700',
      priority: 'Medium',
      priorityColor: 'bg-orange-100 text-orange-700',
    },
    {
      id: 3,
      title: 'Data Dashboard',
      description: 'Analytics dashboard for KPIs and metrics',
      date: 'Mar 1, 2026',
      status: 'Pending',
      statusColor: 'bg-yellow-100 text-yellow-700',
      priority: 'Low',
      priorityColor: 'bg-gray-100 text-gray-700',
    },
    {
      id: 1,
      title: 'Website Redesign',
      description: 'Redesign the company website to improve UX',
      date: 'Feb 3, 2026',
      status: 'In Progress',
      statusColor: 'bg-blue-100 text-blue-700',
      priority: 'High',
      priorityColor: 'bg-red-100 text-red-700',
    },
    {
      id: 2,
      title: 'Mobile App',
      description: 'Build a cross-platform mobile application',
      date: 'Jan 18, 2026',
      status: 'Completed',
      statusColor: 'bg-green-100 text-green-700',
      priority: 'Medium',
      priorityColor: 'bg-orange-100 text-orange-700',
    },
    {
      id: 3,
      title: 'Data Dashboard',
      description: 'Analytics dashboard for KPIs and metrics',
      date: 'Mar 1, 2026',
      status: 'Pending',
      statusColor: 'bg-yellow-100 text-yellow-700',
      priority: 'Low',
      priorityColor: 'bg-gray-100 text-gray-700',
    },
    {
      id: 1,
      title: 'Website Redesign',
      description: 'Redesign the company website to improve UX',
      date: 'Feb 3, 2026',
      status: 'In Progress',
      statusColor: 'bg-blue-100 text-blue-700',
      priority: 'High',
      priorityColor: 'bg-red-100 text-red-700',
    },
    {
      id: 2,
      title: 'Mobile App',
      description: 'Build a cross-platform mobile application',
      date: 'Jan 18, 2026',
      status: 'Completed',
      statusColor: 'bg-green-100 text-green-700',
      priority: 'Medium',
      priorityColor: 'bg-orange-100 text-orange-700',
    },
    {
      id: 3,
      title: 'Data Dashboard',
      description: 'Analytics dashboard for KPIs and metrics',
      date: 'Mar 1, 2026',
      status: 'Pending',
      statusColor: 'bg-yellow-100 text-yellow-700',
      priority: 'Low',
      priorityColor: 'bg-gray-100 text-gray-700',
    },
    {
      id: 1,
      title: 'Website Redesign',
      description: 'Redesign the company website to improve UX',
      date: 'Feb 3, 2026',
      status: 'In Progress',
      statusColor: 'bg-blue-100 text-blue-700',
      priority: 'High',
      priorityColor: 'bg-red-100 text-red-700',
    },
    {
      id: 2,
      title: 'Mobile App',
      description: 'Build a cross-platform mobile application',
      date: 'Jan 18, 2026',
      status: 'Completed',
      statusColor: 'bg-green-100 text-green-700',
      priority: 'Medium',
      priorityColor: 'bg-orange-100 text-orange-700',
    },
    {
      id: 3,
      title: 'Data Dashboard',
      description: 'Analytics dashboard for KPIs and metrics',
      date: 'Mar 1, 2026',
      status: 'Pending',
      statusColor: 'bg-yellow-100 text-yellow-700',
      priority: 'Low',
      priorityColor: 'bg-gray-100 text-gray-700',
    }, {
      id: 1,
      title: 'Website Redesign',
      description: 'Redesign the company website to improve UX',
      date: 'Feb 3, 2026',
      status: 'In Progress',
      statusColor: 'bg-blue-100 text-blue-700',
      priority: 'High',
      priorityColor: 'bg-red-100 text-red-700',
    },
    {
      id: 2,
      title: 'Mobile App',
      description: 'Build a cross-platform mobile application',
      date: 'Jan 18, 2026',
      status: 'Completed',
      statusColor: 'bg-green-100 text-green-700',
      priority: 'Medium',
      priorityColor: 'bg-orange-100 text-orange-700',
    },
    {
      id: 3,
      title: 'Data Dashboard',
      description: 'Analytics dashboard for KPIs and metrics',
      date: 'Mar 1, 2026',
      status: 'Pending',
      statusColor: 'bg-yellow-100 text-yellow-700',
      priority: 'Low',
      priorityColor: 'bg-gray-100 text-gray-700',
    },

  ];
}
